# Madlibs game using the excerpt of The Hobbit

# Get new words from the user
race = input('enter a type of fantastical creature: ')
place = input('enter a place: ')
bug = input('enter a bug: ')
adjective = input('enter an adjective: ')
verb = input('enter a verb: ')
place2 = input('name another place: ')
adjective2 = input('enter another adjective: ')
noun = input('enter a noun: ')
color = input('enter a color: ')
shape = input('enter a shape: ')
noun2 = input('enter another noun: ')
surface = input('name a surface: ')
clothing = input('enter a type of clothing: ')
clothing2 = input('enter another type of clothing: ')
group = input('enter a group of people: \n')

print("An Unexpected Party \n")
print(f"In a hole in the {place} there lived a {race}.")
print(f"Not a nasty, dirty, wet hole, filled with the ends of {bug}s and an oozy smell,")
print(f"nor yet a dry, bare, {adjective} hole with nothing in it to sit down on or to {verb}:")
print(f"it was a {place2}, and that means comfort. \n")
print(f"It had a perfectly {adjective2} {noun} like a porthole, painted {color},")
print(f"with a shiny {color} brass knob in the exact middle.")
print(f"The door opened on to a {shape} shaped hall like a tunnel:")
print(f"a very comfortable tunnel without {noun2}s,")
print(f"with panelled walls, and {surface} tiled and carpeted,")
print(f"provided with polished chairs, and lots and lots of pegs for {clothing}s and {clothing2}s-")
print(f"the {race} was fond of {group}.")
